import { Database } from 'sql.js';
import { saveDb } from './db.js';
import { analyzeWithFallback } from './ai.js';
import fs from 'fs';
import path from 'path';

export interface RawSeedItem {
  content: string;
  rating: number;
  source: string;
  daysAgo: number;
}

export const SAMPLE_FEEDBACK_DATA: RawSeedItem[] = [
  // Search Performance & Usability
  { content: "Search becomes very slow when our workspace exceeds 10,000 records. Page freezes for 3 seconds.", rating: 2, source: "Website", daysAgo: 1 },
  { content: "Every time I search by date range with multiple tags, the query times out with a 504 error.", rating: 1, source: "Web App", daysAgo: 2 },
  { content: "The new Cmd+K global search shortcut is super fast and convenient! Saves me 20 minutes a day.", rating: 5, source: "Web App", daysAgo: 3 },
  { content: "Search filters do not reset when I click the reset button. I have to reload the entire tab.", rating: 2, source: "Website", daysAgo: 4 },
  { content: "Search query results are completely accurate, but the spinner takes 4 seconds to disappear.", rating: 3, source: "Support Ticket", daysAgo: 5 },
  { content: "Can you add fuzzy search? A single typo in a customer email yields zero results.", rating: 3, source: "In-app Widget", daysAgo: 6 },
  { content: "Instant autocomplete on search suggestions works like magic on desktop.", rating: 5, source: "Chrome Extension", daysAgo: 7 },
  { content: "Search indexing seems stuck after our daily bulk update. Takes 2 hours to reflect changes.", rating: 2, source: "Support Ticket", daysAgo: 8 },
  { content: "Filtering by multiple topics works well, but sorting by date resets my search keywords.", rating: 3, source: "Website", daysAgo: 9 },
  { content: "Search bar doesn't have autofocus when opening the modal on Mac Safari.", rating: 3, source: "Web App", daysAgo: 10 },
  { content: "Blazing fast search query response even during peak afternoon hours. Kudos to the team!", rating: 5, source: "Trustpilot", daysAgo: 11 },
  { content: "Search latency spiked noticeably this week. Simple keyword searches take over 5 seconds.", rating: 1, source: "Website", daysAgo: 12 },
  { content: "Regex or boolean search operators (AND/OR/NOT) would be a game changer for power users.", rating: 4, source: "GitHub", daysAgo: 13 },
  { content: "Search query crashes the tab if the input string contains double quotes or backslashes.", rating: 1, source: "Web App", daysAgo: 14 },
  { content: "Clean search interface and intuitive highlight matches in the result snippet.", rating: 5, source: "Website", daysAgo: 15 },

  // CSV Import & Parsing
  { content: "Every time I upload a large CSV file with 5,000 rows, the application freezes and crashes the browser.", rating: 1, source: "Web App", daysAgo: 1 },
  { content: "CSV upload parsed 25,000 rows in just 3 seconds, absolutely blown away by the speed!", rating: 5, source: "Web App", daysAgo: 2 },
  { content: "CSV column auto-detection failed because our headers had trailing spaces. Please trim whitespace.", rating: 3, source: "Website", daysAgo: 3 },
  { content: "Unable to import CSV files encoded in UTF-8 with BOM generated by Microsoft Excel.", rating: 2, source: "Support Ticket", daysAgo: 4 },
  { content: "The CSV mapping modal is so straightforward. Automatically matched 9 out of 10 columns correctly.", rating: 5, source: "Web App", daysAgo: 5 },
  { content: "No progress bar during CSV import. I can't tell if the job is running or hung.", rating: 2, source: "In-app Widget", daysAgo: 6 },
  { content: "Imported 1,500 feedback entries and duplicate detection correctly skipped 42 duplicates. Perfect!", rating: 5, source: "Website", daysAgo: 7 },
  { content: "CSV upload silently drops rows that have commas inside quoted fields.", rating: 2, source: "Support Ticket", daysAgo: 8 },
  { content: "Wish we could schedule recurring CSV imports from an SFTP server or cloud bucket.", rating: 4, source: "Web App", daysAgo: 9 },
  { content: "The sample CSV template provided on the import page made our migration effortless.", rating: 5, source: "Website", daysAgo: 10 },
  { content: "CSV import failed with 'Payload Too Large' on a 15MB file. Is there a size limit?", rating: 2, source: "Support Ticket", daysAgo: 11 },
  { content: "Great error summary after import showing exactly which 3 rows had invalid dates.", rating: 4, source: "Web App", daysAgo: 12 },
  { content: "Import modal backdrop clicks dismiss the modal and lose my column mappings.", rating: 2, source: "Website", daysAgo: 13 },
  { content: "Bulk export to CSV is clean and opens seamlessly in Google Sheets.", rating: 5, source: "Web App", daysAgo: 14 },
  { content: "Drag and drop CSV zone didn't recognize .tsv files even though the docs say delimiter auto-detects.", rating: 3, source: "Website", daysAgo: 15 },

  // Mobile Navigation & Viewport
  { content: "On iPhone 15 Safari, the navigation drawer gets stuck halfway when swiping quickly.", rating: 2, source: "Mobile", daysAgo: 1 },
  { content: "Mobile responsive layout is surprisingly clean. I can review high-priority alerts on my phone easily.", rating: 5, source: "Mobile", daysAgo: 2 },
  { content: "Table columns overflow horizontally on mobile screens and there is no swipe indicator.", rating: 2, source: "Mobile", daysAgo: 3 },
  { content: "The bottom navigation bar overlaps with the action buttons on iOS home bar indicator.", rating: 2, source: "Mobile", daysAgo: 4 },
  { content: "Smooth touch gestures on KPI cards and charts render beautifully on tablet screen.", rating: 4, source: "Mobile", daysAgo: 5 },
  { content: "Dropdown menus close immediately when scrolling vertically on Android Chrome.", rating: 2, source: "Mobile", daysAgo: 6 },
  { content: "Filter modal takes over the entire mobile screen without an easy escape or back button.", rating: 2, source: "Mobile", daysAgo: 7 },
  { content: "Push notification deep links on mobile open the login screen instead of the target feedback item.", rating: 2, source: "Mobile", daysAgo: 8 },
  { content: "Very snappy responsive transitions between views on iPad Pro.", rating: 5, source: "Mobile", daysAgo: 9 },
  { content: "Touch targets for delete buttons on mobile table rows are too small, keep misclicking.", rating: 2, source: "Mobile", daysAgo: 10 },

  // Authentication & Security
  { content: "Session expires after 15 minutes of inactivity and wipes out whatever draft decision I was typing.", rating: 2, source: "Web App", daysAgo: 1 },
  { content: "Google Workspace SSO login was instant and picked up our enterprise domain permissions.", rating: 5, source: "Web App", daysAgo: 2 },
  { content: "2FA authentication code input doesn't auto-advance to the next digit box.", rating: 3, source: "Website", daysAgo: 3 },
  { content: "Password reset emails took 45 minutes to arrive in Outlook inbox.", rating: 2, source: "Support Ticket", daysAgo: 4 },
  { content: "Role-based permissions work smoothly. Read-only viewers cannot accidentally edit decisions.", rating: 5, source: "Web App", daysAgo: 5 },
  { content: "Logged out abruptly in the middle of generating a quarterly report.", rating: 1, source: "Web App", daysAgo: 6 },
  { content: "API key generation with scoped permissions is well thought out and secure.", rating: 5, source: "Web App", daysAgo: 7 },
  { content: "Can we support SAML / Okta for enterprise single sign-on?", rating: 4, source: "Support Ticket", daysAgo: 8 },

  // Dashboard & Analytics
  { content: "Dashboard loads all metrics in under 400ms. The KPI trends give me immediate clarity.", rating: 5, source: "Web App", daysAgo: 1 },
  { content: "Dashboard performance degrades heavily on Mondays when all department leads view charts at once.", rating: 2, source: "Web App", daysAgo: 2 },
  { content: "Love the sentiment donut chart with real percentage breakdown. High visual clarity.", rating: 5, source: "Website", daysAgo: 3 },
  { content: "Date range selector on dashboard doesn't remember my last selected '30 Days' preference.", rating: 3, source: "Web App", daysAgo: 4 },
  { content: "The feedback volume trend line chart makes executive presentations 10x easier.", rating: 5, source: "Trustpilot", daysAgo: 5 },
  { content: "Summary metrics on total feedback mismatch slightly with table row count when filters are active.", rating: 3, source: "Support Ticket", daysAgo: 6 },
  { content: "Executive AI Product Summary section saves our product team 5 hours of manual analysis every sprint.", rating: 5, source: "Web App", daysAgo: 7 },
  { content: "Would love to export dashboard charts directly as SVG or PNG images for slides.", rating: 4, source: "Website", daysAgo: 8 },
  { content: "Tooltips on the sentiment timeline chart overlap when two data points are close together.", rating: 3, source: "Web App", daysAgo: 9 },
  { content: "Real-time updates on high-priority issues helped us catch a checkout bug within 20 minutes.", rating: 5, source: "Website", daysAgo: 10 },

  // Decisions & Actionability
  { content: "The 'Turn recurring problems into decisions' workflow is the best feature in this entire tool.", rating: 5, source: "Web App", daysAgo: 1 },
  { content: "Decisions status transitions (New -> Planned -> In Progress) are clear and keep our team aligned.", rating: 5, source: "Web App", daysAgo: 2 },
  { content: "I wish I could link Jira issue tickets directly to product decision cards.", rating: 4, source: "In-app Widget", daysAgo: 3 },
  { content: "Decision priority filters are helpful, but would like to filter by affected feature as well.", rating: 4, source: "Website", daysAgo: 4 },
  { content: "Created 8 decisions from last week's CSV upload and the engineering team prioritized them instantly.", rating: 5, source: "Web App", daysAgo: 5 },
  { content: "Would like to assign decision cards to specific team members with due dates.", rating: 4, source: "Support Ticket", daysAgo: 6 },
  { content: "AI suggested action for search latency was spot-on. Adding database index fixed it completely.", rating: 5, source: "Trustpilot", daysAgo: 7 },
  { content: "Deleted decisions cannot be restored. An undo or archive option would prevent accidental loss.", rating: 3, source: "Web App", daysAgo: 8 },

  // Reports & Exports
  { content: "Generated a comprehensive 30-day feedback intelligence report in 2 seconds. Clean formatting!", rating: 5, source: "Web App", daysAgo: 1 },
  { content: "PDF export formatting breaks when feedback comments contain long URLs without spaces.", rating: 2, source: "Support Ticket", daysAgo: 2 },
  { content: "CSV report export contains all raw columns, sentiment scores, and AI summaries cleanly.", rating: 5, source: "Website", daysAgo: 3 },
  { content: "Can we customize the logo and brand header in generated PDF reports?", rating: 4, source: "Web App", daysAgo: 4 },
  { content: "The executive report preview gives our stakeholders instant confidence in roadmap priorities.", rating: 5, source: "Trustpilot", daysAgo: 5 },
  { content: "Scheduled automated weekly email reports would make this irreplaceable.", rating: 4, source: "In-app Widget", daysAgo: 6 },

  // UI & Design System
  { content: "The light mode typography and soft border hierarchy look like a top-tier modern SaaS product.", rating: 5, source: "Website", daysAgo: 1 },
  { content: "Secondary text color in the table header has low contrast in bright daylight conditions.", rating: 3, source: "Website", daysAgo: 2 },
  { content: "Smooth hover animations on cards feel premium without being slow or distracting.", rating: 5, source: "Web App", daysAgo: 3 },
  { content: "Dark mode option would be greatly appreciated for late night triage sessions.", rating: 4, source: "In-app Widget", daysAgo: 4 },
  { content: "Empty state illustrations and guided CTAs make initial onboarding crystal clear.", rating: 5, source: "Website", daysAgo: 5 },
  { content: "Table row height feels a bit too cramped when reviewing multi-line customer testimonials.", rating: 3, source: "Web App", daysAgo: 6 },

  // Integrations & Webhooks
  { content: "Slack notification webhook triggers instantly whenever a High Priority issue is logged.", rating: 5, source: "Web App", daysAgo: 1 },
  { content: "Webhook retry mechanism lacks exponential backoff when our staging server restarts.", rating: 3, source: "GitHub", daysAgo: 2 },
  { content: "Zapier integration connected our Zendesk tickets to ProductPulse in under 5 minutes.", rating: 5, source: "Support Ticket", daysAgo: 3 },
  { content: "API documentation has clear cURL examples and schema definitions for all feedback endpoints.", rating: 5, source: "Website", daysAgo: 4 },
  { content: "Rate limiting header (X-RateLimit-Remaining) should be returned in API responses.", rating: 4, source: "GitHub", daysAgo: 5 },

  // Billing & Subscriptions
  { content: "Transparent pricing tier and smooth upgrade workflow when adding extra team seats.", rating: 5, source: "Website", daysAgo: 1 },
  { content: "Invoice PDF download showed incorrect tax identification number on European invoices.", rating: 2, source: "Support Ticket", daysAgo: 2 },
  { content: "Usage meter for AI feedback analysis tokens clearly shows remaining monthly balance.", rating: 5, source: "Web App", daysAgo: 3 },
  { content: "Annual billing discount with credit card payment went through without any hitch.", rating: 5, source: "Website", daysAgo: 4 },

  // Additional Real-World Software Feedback
  { content: "Application crashes when pasting formatted rich text into the feedback manual entry box.", rating: 1, source: "Website", daysAgo: 1 },
  { content: "The sentiment analysis accurately tagged sarcastic feedback as negative. Very impressive AI!", rating: 5, source: "Trustpilot", daysAgo: 2 },
  { content: "Filter by sentiment: Negative, topic: Search, priority: High instantly isolated our biggest fire.", rating: 5, source: "Web App", daysAgo: 3 },
  { content: "Keyboard navigation across feedback list with arrow keys works seamlessly.", rating: 5, source: "Web App", daysAgo: 4 },
  { content: "Date format should respect user browser locale (DD/MM/YYYY vs MM/DD/YYYY).", rating: 3, source: "Website", daysAgo: 5 },
  { content: "Browser back button from feedback detail view resets all active dashboard filters.", rating: 2, source: "Web App", daysAgo: 6 },
  { content: "High priority alert badges are clearly distinguishable even for colorblind team members.", rating: 5, source: "Web App", daysAgo: 7 },
  { content: "Multi-select bulk actions to tag or delete multiple feedback rows would speed up triage.", rating: 4, source: "Website", daysAgo: 8 },
  { content: "Loading skeleton states prevent layout shifts while data is fetching. Very polished feel.", rating: 5, source: "Web App", daysAgo: 9 },
  { content: "Exporting filtered search results retains exact filter criteria in generated CSV header.", rating: 5, source: "Web App", daysAgo: 10 },
  { content: "Customer support responded in 12 minutes when we had questions regarding CSV column headers.", rating: 5, source: "Support Ticket", daysAgo: 11 },
  { content: "Initial onboarding walkthrough was concise and showed the value proposition in 60 seconds.", rating: 5, source: "Website", daysAgo: 12 },
  { content: "Occasional 502 Bad Gateway during heavy midnight data syncs.", rating: 2, source: "Support Ticket", daysAgo: 13 },
  { content: "Clean API payload structure makes custom webhook ingestion trivial to write in Python.", rating: 5, source: "GitHub", daysAgo: 14 },
  { content: "The AI summary card is the first thing our leadership team checks in our Monday standup.", rating: 5, source: "Trustpilot", daysAgo: 15 },
  { content: "Search autocomplete drops focus if a toast notification appears concurrently.", rating: 2, source: "Web App", daysAgo: 16 },
  { content: "CSV parser handles UTF-8 characters and accented names without mangling characters.", rating: 5, source: "Web App", daysAgo: 17 },
  { content: "Priority score calculation accurately reflects customer frustration severity.", rating: 5, source: "Trustpilot", daysAgo: 18 },
  { content: "Mobile drawer animation drops frames on low-powered Android devices.", rating: 2, source: "Mobile", daysAgo: 19 },
  { content: "Breadcrumb navigation on detail view allows fast return to the exact filtered table state.", rating: 5, source: "Web App", daysAgo: 20 },
  { content: "Would like to filter feedback by customer company tier (Enterprise vs Free vs Pro).", rating: 4, source: "In-app Widget", daysAgo: 21 },
  { content: "Clear visual hierarchy between primary call to actions and secondary filters.", rating: 5, source: "Website", daysAgo: 22 },
  { content: "Token expiration warning banner allows 1-click session renewal without losing inputs.", rating: 5, source: "Web App", daysAgo: 23 },
  { content: "Column sorting in table doesn't have an indicator for descending vs ascending sort order.", rating: 3, source: "Web App", daysAgo: 24 },
  { content: "Fastest feedback analysis platform we have used. Reduced our sprint planning time by half.", rating: 5, source: "Trustpilot", daysAgo: 25 },
];

export async function seedDatabase(db: Database) {
  // Check if products already exist
  const res = db.exec("SELECT COUNT(*) as cnt FROM products;");
  const count = res[0]?.values[0]?.[0] as number || 0;
  if (count > 0) {
    return; // Already seeded
  }

  console.log('Seeding initial ProductPulse demo dataset...');

  // Create default product and demo dataset
  const productId = 'prod_saas_flow_1';
  const datasetId = 'ds_demo_saas_flow';

  db.run(`
    INSERT OR REPLACE INTO datasets (id, name, filename, row_count, analysis_status)
    VALUES (?, ?, ?, ?, ?);
  `, [datasetId, 'SaaS Flow Analytics [Demo]', 'demo-feedback.csv', SAMPLE_FEEDBACK_DATA.length, 'completed']);

  db.run(`
    INSERT OR REPLACE INTO products (id, name, slug, description)
    VALUES (?, ?, ?, ?);
  `, [productId, 'SaaS Flow Analytics', 'saas-flow', 'Modern web-based product analytics and user tracking platform.']);

  // Insert seed feedback
  const now = new Date();
  
  for (let i = 0; i < SAMPLE_FEEDBACK_DATA.length; i++) {
    const item = SAMPLE_FEEDBACK_DATA[i];
    const itemDate = new Date(now.getTime() - item.daysAgo * 24 * 60 * 60 * 1000);
    const dateStr = itemDate.toISOString().split('T')[0];

    const analysis = analyzeWithFallback(item.content, item.rating);
    const id = `fb_${String(i + 1).padStart(4, '0')}`;

    db.run(`
      INSERT INTO feedback (
        id, dataset_id, product_id, content, rating, source, date,
        sentiment, sentiment_score, sentiment_confidence,
        topic, priority, issue_group, ai_summary,
        detected_problem, possible_cause, user_impact, suggested_action
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
    `, [
      id,
      datasetId,
      productId,
      item.content,
      item.rating,
      item.source,
      dateStr,
      analysis.sentiment,
      analysis.sentiment_score,
      analysis.sentiment_confidence,
      analysis.topic,
      analysis.priority,
      analysis.issue_group,
      analysis.ai_summary,
      analysis.detected_problem,
      analysis.possible_cause,
      analysis.user_impact,
      analysis.suggested_action,
    ]);
  }

  // Pre-seed product decisions
  const defaultDecisions = [
    {
      id: 'dec_001',
      product_id: productId,
      title: 'Improve Search Performance with Server-Side Indexing',
      affected_feature: 'Search',
      priority: 'high',
      trend: 'increasing',
      supporting_feedback_count: 142,
      suggested_action: 'Add composite indexes on (workspace_id, title, content) and implement 250ms client-side debouncing.',
      status: 'Planned',
    },
    {
      id: 'dec_002',
      product_id: productId,
      title: 'Transition Large CSV Ingestion to Background Worker Queue',
      affected_feature: 'CSV Upload',
      priority: 'high',
      trend: 'increasing',
      supporting_feedback_count: 96,
      suggested_action: 'Stream files into chunked background jobs and provide persistent real-time progress indicators.',
      status: 'In Progress',
    },
    {
      id: 'dec_003',
      product_id: productId,
      title: 'Optimize Mobile Viewport and Swipe Navigation Drawer',
      affected_feature: 'Mobile',
      priority: 'medium',
      trend: 'stable',
      supporting_feedback_count: 71,
      suggested_action: 'Refactor drawer gesture handlers to use passive touch events and fix iOS Safari backdrop blur.',
      status: 'Reviewing',
    },
    {
      id: 'dec_004',
      product_id: productId,
      title: 'Implement Silent OAuth Token Refresh Before Expiry',
      affected_feature: 'Authentication',
      priority: 'medium',
      trend: 'decreasing',
      supporting_feedback_count: 54,
      suggested_action: 'Trigger background token refresh at 80% TTL and cache user form drafts in local storage.',
      status: 'Completed',
    },
    {
      id: 'dec_005',
      product_id: productId,
      title: 'Cache Dashboard Metrics and Optimize Aggregate SQL Queries',
      affected_feature: 'Dashboard',
      priority: 'medium',
      trend: 'stable',
      supporting_feedback_count: 42,
      suggested_action: 'Precompute 24-hour KPI rollups and enable incremental cache invalidation.',
      status: 'Planned',
    },
  ];

  for (const d of defaultDecisions) {
    db.run(`
      INSERT INTO decisions (
        id, dataset_id, product_id, title, affected_feature, priority, trend,
        supporting_feedback_count, suggested_action, status
      ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
    `, [
      d.id,
      datasetId,
      d.product_id,
      d.title,
      d.affected_feature,
      d.priority,
      d.trend,
      d.supporting_feedback_count,
      d.suggested_action,
      d.status,
    ]);
  }

  saveDb();
  console.log(`Database seeded successfully with ${SAMPLE_FEEDBACK_DATA.length} feedback items and ${defaultDecisions.length} decisions.`);

  // Also write public sample CSV file so users can download it directly from UI
  try {
    const csvHeader = 'Feedback,Rating,Date,Source,Product\n';
    const csvRows = SAMPLE_FEEDBACK_DATA.map((item, idx) => {
      const itemDate = new Date(now.getTime() - item.daysAgo * 24 * 60 * 60 * 1000);
      const dateStr = itemDate.toISOString().split('T')[0];
      const escaped = `"${item.content.replace(/"/g, '""')}"`;
      return `${escaped},${item.rating},${dateStr},${item.source},SaaS Flow Analytics`;
    }).join('\n');

    const publicDir = path.resolve(process.cwd(), 'public');
    if (!fs.existsSync(publicDir)) {
      fs.mkdirSync(publicDir, { recursive: true });
    }
    fs.writeFileSync(path.resolve(publicDir, 'sample-feedback.csv'), csvHeader + csvRows, 'utf8');
  } catch (err) {
    console.warn('Could not write public/sample-feedback.csv:', err);
  }
}
